/*

	UTILITY TO DROP OR CREATE CONSTRAINTS

*/

-- DROP constraints
ALTER TABLE [dbo].[JOB_MONITOR_EVENT_OPTION] 
	DROP CONSTRAINT IF EXISTS FK_JOB_MONITOR_EVENT_OPTION_JOB_MONITOR_ID;

ALTER TABLE [dbo].[JOB_LAUNCH_QUEUE]
	DROP CONSTRAINT IF EXISTS FK_JOB_LAUNCH_QUEUE_JOB_MONITOR_EVENT_OPTION;


-- CREATE constraints
-- TO DO
