CREATE UNIQUE INDEX [UX_JOB_MONITOR_EVENT_OPTION]
	ON [dbo].[JOB_MONITOR_EVENT_OPTION] (
		[JOB_MONITOR_ID]
	,	[JOB_MONITOR_EVENT_ID]	
	,	[JOB_ID_TO_LAUNCH]
	)
	WITH ( IGNORE_DUP_KEY = ON );

