CREATE TABLE [dbo].[JOB_MONITOR_EVENT]
(
	[JOB_MONITOR_EVENT_ID] INT IDENTITY NOT NULL
		CONSTRAINT PK_JOB_MONITOR_EVENT PRIMARY KEY CLUSTERED
,	[JOB_MONITOR_EVENT_DESCRIPTION]	VARCHAR(50) NOT NULL
,	[LAST_MODIFIED]		DATETIME NOT NULL
		CONSTRAINT DF_JOB_MONITOR_EVENT_LAST_MODIFIED
			DEFAULT GETDATE()
)
