CREATE TABLE [dbo].[JOB_MONITOR]
(
	[JOB_MONITOR_ID]	INT IDENTITY NOT NULL
		CONSTRAINT PK_JOB_MONITOR PRIMARY KEY CLUSTERED
,	[JOB_ID]			UNIQUEIDENTIFIER NOT NULL
,	[JOB_STEP_UID]		UNIQUEIDENTIFIER NULL
,	[ENABLED]			INT NOT NULL
		CONSTRAINT DF_JOB_MONITOR_ENABLED
			DEFAULT 1
,	[LAST_MODIFIED]		DATETIME NOT NULL
		CONSTRAINT DF_JOB_MONITOR_LAST_MODIFIED
			DEFAULT GETDATE()
)
