CREATE TABLE [dbo].[JOB_LAUNCH_QUEUE]
(
	[JOB_LAUNCH_QUEUE_ID] INT IDENTITY NOT NULL 
		CONSTRAINT PK_JOB_LAUNCH_QUEUE PRIMARY KEY CLUSTERED
,	[JOB_MONITOR_EVENT_OPTION_ID]	INT NOT NULL
		CONSTRAINT FK_JOB_LAUNCH_QUEUE_JOB_MONITOR_EVENT_OPTION
			FOREIGN KEY REFERENCES 
				[dbo].[JOB_MONITOR_EVENT_OPTION](JOB_MONITOR_EVENT_OPTION_ID)
,	[QUEUE_TIME]					DATETIME NOT NULL
		CONSTRAINT DF_JOB_LAUNCH_QUEUE_QUEUE_TIME
			DEFAULT GETDATE()
,	[JOB_LAUNCH_TIME]				DATETIME NOT NULL
		CONSTRAINT DF_JOB_LAUNCH_QUEUE_JOB_LAUNCH_TIME
			DEFAULT GETDATE()
,	[LAST_MODIFIED]					DATETIME NOT NULL
		CONSTRAINT DF_JOB_LAUNCH_QUEUE_LAST_MODIFIED
			DEFAULT GETDATE()
)
