CREATE TABLE [dbo].[JOB_LAUNCH_LOG]
(
	[JOB_LAUNCH_LOG_ID]		INT IDENTITY NOT NULL 
		CONSTRAINT PK_JOB_LAUNCH_LOG
			PRIMARY KEY CLUSTERED
,	[JOB_LAUNCH_QUEUE_ID]	INT NOT NULL
,	[RUN_TIME]				DATETIME NOT NULL		
)
