CREATE TABLE [dbo].[QUEUE_JOB_LOG]
(
	[QUEUE_JOB_LOG_ID] INT IDENTITY NOT NULL
		CONSTRAINT PK_QUEUE_JOB_LOG PRIMARY KEY CLUSTERED
,	[RUN_TIME]			DATETIME NOT NULL
		CONSTRAINT DF_QUEUE_JOB_LOG_RUN_TIME
			DEFAULT GETDATE()
,	[MAX_INSTANCE_ID]	INT NOT NULL
,	[ROW_COUNT]			INT NOT NULL
)
