CREATE TABLE [dbo].[QUEUE_JOBS_TO_LAUNCH_STAGING]
(
	[INSTANCE_ID]	INT NOT NULL 
,	[JOB_ID]		UNIQUEIDENTIFIER NOT NULL
,	[STEP_ID]		INT NOT NULL
,	[RUN_STATUS]	INT NOT NULL
,	[START_TIME]	DATETIME NOT NULL
,	[END_TIME]		DATETIME NOT NULL
,	[SERVER]		SYSNAME NOT NULL
)
