CREATE OR ALTER PROCEDURE [dbo].[CHECK_RUN_WEEKLY_REPORT]
	@P_TODAY		DATE = NULL
,	@P_RUN_REPORT	INT OUTPUT
AS
BEGIN
	DECLARE
		@TODAY DATE = IIF(@P_TODAY IS NULL, GETDATE(), @P_TODAY);

	DECLARE
		@CURRENT_WEEK   INT = DATEPART(week, @TODAY)
	 ,	@LAST_MONTH_END_WEEK INT = 
			DATEPART(week, DATEADD(day, 1, EOMONTH(@TODAY, -1)))
	 ,	@NEXT_MONTH_END_WEEK INT = 
			DATEPART(week, DATEADD(day, 1, EOMONTH(@TODAY)));

	IF @CURRENT_WEEK > @LAST_MONTH_END_WEEK AND 
		@CURRENT_WEEK < @NEXT_MONTH_END_WEEK
		SET @P_RUN_REPORT = 1;	-- run the report
	ELSE
		SET @P_RUN_REPORT = 0;	-- do not run the report
END



